print("Asmi.bae is my name!")
print("My goal is to fulfill my father's dream!")
print("I want to be a successful programmer!")
print("I want to make my parents proud!")
print("I want to be a good human being!")
print("I want to be a good daughter!")
print("I want to be a good sister!")
print("I want to be a good friend!")
print("I want to be a good student!")
print("I want to be a good citizen!")
print("I want to be a good person!")
print("I want to be a good role model!")
print("I want to be a good influence!")
print("I want to be a good example!")
print("I want to be a good leader!")
print("I want to be a good programmer!")
print( "Hi,asmi.bae!" )
print("I want to be a good coder!")
print("I want to be a good developer!")
print("I want to be a good engineer!")
